export interface ApiResponse<T> {
  data: T | null; // Generic type for the response data, can be null
  message: string; // Message string from the response
}

export interface MessageDTO {
  id?: number; // Message ID, auto-generated by the backend
  senderId: number; // Sender's user ID, handled by the backend (don't set this on frontend)
  senderUsername: string;
  receiverId: number | null; // The ID of the friend you're messaging, can be null for group messages
  channelId: number | null; // The ID of the channel (if it's a group message), null for direct messages
  messageText: string; // The content of the message
  createdAt: string; // Timestamp when the message was sent, in ISO string format
}
